// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PatternMapper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPatternMapperPackageString = "5bb6aee6-9899-496d-aa49-15c86deb1e16";
        public static Guid guidPatternMapperPackage = new Guid(guidPatternMapperPackageString);

        public const string guidPatternMapperPackageCmdSetString = "f5d441d3-88e5-456f-9fda-e1f72b62a14d";
        public static Guid guidPatternMapperPackageCmdSet = new Guid(guidPatternMapperPackageCmdSetString);

        public const string guidImagesString = "84312280-9d15-4e2a-9302-1609ef0d5fd0";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PatternMapperToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}